### ISSUE TITLE
Update CI

### ISSUE THREAD

**Issue by bHimes** [bHimes/cisTEMx#45]
CI should

1. update to work with ubuntu 20 and g++11
2. not bother with clang and icpc, instead do a release/debug and possibly a +/- experimental build
3. anything else?

**Comment by bHimes** [comment]
@jojoelfe thoughts? Particularly on combinations of configure options?

**Comment by jojoelfe** [comment]
I think a release/debug is enough. I don't see why you would want a cutting edge build without experimental options. Maybe +/- GPU?

**Comment by bHimes** [comment]
fair. Since we are a bit stuck on the gpu side, what if we proceed with cpu workflow on PR and add a local side workflow that acts by checking for updates to main? 

Sure it is better to catch everything *b4* it is merged in, but we also aren't worried about 10k downloads between merging and a possible post merge workflow/check.

So what if we do a simple release/debug CI on PR and figure out a more complete (+gpu etc) that somehow runs post merge, but still catches problems on the time scale of +\- a day worst case. Then changes are still fresh in mind and easily fixed

**Comment by jojoelfe** [comment]
I think compiling cuda code on Github Actions is no problem, just the testing:

https://github.com/ptheywood/cuda-cmake-github-actions

**Comment by bHimes** [comment]
that makes sense, i was (mis)thinking the driver would be required 

Does the docker container have to be built for every workflow, or could it be pulled like other resources?

That would simplify/ Speed things up quite a bit since the cuda toolkit is pretty hefty

**Comment by jojoelfe** [comment]
The container has to be build only once. Then you can publish it to dockerhub and the workflow pulls it from there,

**Comment by bHimes** [comment]
thats great! also solves our test data problem too. Will you have time to talk a bit about the container design while on campus tomorrow?
